"""empty message

Revision ID: 068ea3fb2c42
Revises: 49d6517d5142
Create Date: 2022-01-29 21:31:30.323502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068ea3fb2c42'
down_revision = '49d6517d5142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_records', sa.Column('province', sa.String(), nullable=True))
    op.execute("UPDATE activity_records SET province = 'empty'")
    op.alter_column('activity_records', 'province', nullable=False)
    op.add_column('activity_records', sa.Column('town', sa.String(), nullable=True))
    op.execute("UPDATE activity_records SET town = 'empty'")
    op.alter_column('activity_records', 'town', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_records', 'town')
    op.drop_column('activity_records', 'province')
    # ### end Alembic commands ###
