"""empty message

Revision ID: 0822d6ca5f2c
Revises: 7dd6c82c700b
Create Date: 2022-02-06 11:20:07.993745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0822d6ca5f2c'
down_revision = '7dd6c82c700b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_records', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    op.alter_column('activity_records', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
