"""empty message

Revision ID: 08bc8ed1b491
Revises: 4d9557df20d8
Create Date: 2022-02-10 19:15:00.471749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bc8ed1b491'
down_revision = '4d9557df20d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_records', 'region', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_records', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
