"""empty message

Revision ID: 3b761d9f8f82
Revises: 
Create Date: 2022-01-07 15:37:59.846375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b761d9f8f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tel', sa.String(), nullable=True))
    op.drop_constraint('users_email1_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'email2')
    op.drop_column('users', 'tel2')
    op.drop_column('users', 'tel1')
    op.drop_column('users', 'email1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tel1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tel2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email1_key', 'users', ['email1'])
    op.drop_column('users', 'tel')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
