"""empty message

Revision ID: 49d6517d5142
Revises: 092a1dcb9bbc
Create Date: 2022-01-12 19:50:23.446372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d6517d5142'
down_revision = '092a1dcb9bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET deleted = false")
    op.alter_column('users', 'deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
