"""empty message

Revision ID: 4d9557df20d8
Revises: 1a16252d12fd
Create Date: 2022-02-09 20:19:35.308996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9557df20d8'
down_revision = '1a16252d12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_records', sa.Column('region', sa.String(), nullable=False, server_default=''))
    op.alter_column('activity_records', 'region', server_default=None)
    op.alter_column('activity_records', 'province', nullable=False, server_default='')
    op.alter_column('activity_records', 'region', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_records', 'region')
    # ### end Alembic commands ###
