"""empty message

Revision ID: 56c83dda1879
Revises: 068ea3fb2c42
Create Date: 2022-01-30 19:04:57.358340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c83dda1879'
down_revision = '068ea3fb2c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_records', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('province', sa.String(), nullable=True))
    op.add_column('users', sa.Column('town', sa.String(), nullable=True))
    op.drop_column('users', 'zip')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'town')
    op.drop_column('users', 'province')
    op.alter_column('activity_records', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
