"""empty message

Revision ID: 7dd6c82c700b
Revises: 56c83dda1879
Create Date: 2022-01-30 19:13:13.159311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd6c82c700b'
down_revision = '56c83dda1879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'born_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('born_in', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
