"""empty message

Revision ID: c76254c15efd
Revises: 2e3732038033
Create Date: 2022-02-11 19:56:17.192611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76254c15efd'
down_revision = '2e3732038033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_types', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_types', type_='unique')
    # ### end Alembic commands ###
