"""empty message

Revision ID: f15d8c14ee32
Revises: 0822d6ca5f2c
Create Date: 2022-02-06 14:28:20.642725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15d8c14ee32'
down_revision = '0822d6ca5f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'region', existing_type=sa.VARCHAR())
    op.execute("UPDATE users SET region = ''")
    op.alter_column('users', 'region', nullable=False)

    op.alter_column('users', 'province', existing_type=sa.VARCHAR())
    op.execute("UPDATE users SET province = ''")
    op.alter_column('users', 'province', nullable=False)

    op.alter_column('users', 'town', existing_type=sa.VARCHAR())
    op.execute("UPDATE users SET town = ''")
    op.alter_column('users', 'town', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'province',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
